#server.servlet.context-path=/api/v1.0
#
#spring.datasource.url=jdbc:mysql://app-postgres:3306/mohamed
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=mohamed
#spring.datasource.password=mohamed
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.hibernate.ddl-auto=update

server:
  servlet:
    context-path: /api/v1.0

spring:

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://app-postgres:3306/mohamed
    username: mohamed
    password: mohamed
    driver-class-name: com.mysql.jdbc.Driver
#  config:
#    activate:
#      on-profile: container

